"""fix: Update colume for profile table

Revision ID: 4970d924d54a
Revises: a0ef5f301be7
Create Date: 2025-12-04 21:55:59.211438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4970d924d54a'
down_revision: Union[str, Sequence[str], None] = 'a0ef5f301be7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('language_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('profiles', sa.Column('career', sa.Enum('NEWCOMER', 'YEAR_1_LESS', 'YEAR_1', 'YEAR_2_LESS', 'YEAR_2', 'YEAR_3_LESS', 'YEAR_3', 'YEAR_5_LESS', 'YEAR_5', 'YEAR_7_LESS', 'YEAR_7', 'YEAR_10_LESS', 'YEAR_10', 'YEAR_10_MORE', name='careerenum', native_enum=False, length=20), nullable=True))
    op.create_index(op.f('ix_profiles_career'), 'profiles', ['career'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_career'), table_name='profiles')
    op.drop_column('profiles', 'career')
    op.drop_column('profiles', 'language_skills')
    # ### end Alembic commands ###
