"""feat: Add resume table with relations 

Revision ID: 4e76819351e2
Revises: 31f887c48484
Create Date: 2025-11-15 14:33:55.223854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e76819351e2'
down_revision: Union[str, Sequence[str], None] = '31f887c48484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('profile_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_id'), 'resumes', ['id'], unique=False)
    op.create_index(op.f('ix_resumes_profile_url'), 'resumes', ['profile_url'], unique=False)
    op.create_index(op.f('ix_resumes_title'), 'resumes', ['title'], unique=False)
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=False)
    op.create_table('career_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_working', sa.Boolean(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('position_title', sa.String(), nullable=True),
    sa.Column('main_role', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_history_company_name'), 'career_history', ['company_name'], unique=False)
    op.create_index(op.f('ix_career_history_department'), 'career_history', ['department'], unique=False)
    op.create_index(op.f('ix_career_history_end_date'), 'career_history', ['end_date'], unique=False)
    op.create_index(op.f('ix_career_history_id'), 'career_history', ['id'], unique=False)
    op.create_index(op.f('ix_career_history_is_working'), 'career_history', ['is_working'], unique=False)
    op.create_index(op.f('ix_career_history_main_role'), 'career_history', ['main_role'], unique=False)
    op.create_index(op.f('ix_career_history_position_title'), 'career_history', ['position_title'], unique=False)
    op.create_index(op.f('ix_career_history_resume_id'), 'career_history', ['resume_id'], unique=False)
    op.create_index(op.f('ix_career_history_start_date'), 'career_history', ['start_date'], unique=False)
    op.create_table('introduction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_introduction_content'), 'introduction', ['content'], unique=False)
    op.create_index(op.f('ix_introduction_id'), 'introduction', ['id'], unique=False)
    op.create_index(op.f('ix_introduction_resume_id'), 'introduction', ['resume_id'], unique=False)
    op.create_index(op.f('ix_introduction_title'), 'introduction', ['title'], unique=False)
    op.create_table('language_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('language_type', sa.String(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_language_skills_id'), 'language_skills', ['id'], unique=False)
    op.create_index(op.f('ix_language_skills_language_type'), 'language_skills', ['language_type'], unique=False)
    op.create_index(op.f('ix_language_skills_level'), 'language_skills', ['level'], unique=False)
    op.create_index(op.f('ix_language_skills_resume_id'), 'language_skills', ['resume_id'], unique=False)
    op.create_table('licenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('license_name', sa.String(), nullable=True),
    sa.Column('license_agency', sa.String(), nullable=True),
    sa.Column('license_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licenses_id'), 'licenses', ['id'], unique=False)
    op.create_index(op.f('ix_licenses_license_agency'), 'licenses', ['license_agency'], unique=False)
    op.create_index(op.f('ix_licenses_license_date'), 'licenses', ['license_date'], unique=False)
    op.create_index(op.f('ix_licenses_license_name'), 'licenses', ['license_name'], unique=False)
    op.create_index(op.f('ix_licenses_resume_id'), 'licenses', ['resume_id'], unique=False)
    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('school_name', sa.String(), nullable=False),
    sa.Column('major_name', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_graduated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schools_end_date'), 'schools', ['end_date'], unique=False)
    op.create_index(op.f('ix_schools_id'), 'schools', ['id'], unique=False)
    op.create_index(op.f('ix_schools_is_graduated'), 'schools', ['is_graduated'], unique=False)
    op.create_index(op.f('ix_schools_major_name'), 'schools', ['major_name'], unique=False)
    op.create_index(op.f('ix_schools_resume_id'), 'schools', ['resume_id'], unique=False)
    op.create_index(op.f('ix_schools_school_name'), 'schools', ['school_name'], unique=False)
    op.create_index(op.f('ix_schools_start_date'), 'schools', ['start_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schools_start_date'), table_name='schools')
    op.drop_index(op.f('ix_schools_school_name'), table_name='schools')
    op.drop_index(op.f('ix_schools_resume_id'), table_name='schools')
    op.drop_index(op.f('ix_schools_major_name'), table_name='schools')
    op.drop_index(op.f('ix_schools_is_graduated'), table_name='schools')
    op.drop_index(op.f('ix_schools_id'), table_name='schools')
    op.drop_index(op.f('ix_schools_end_date'), table_name='schools')
    op.drop_table('schools')
    op.drop_index(op.f('ix_licenses_resume_id'), table_name='licenses')
    op.drop_index(op.f('ix_licenses_license_name'), table_name='licenses')
    op.drop_index(op.f('ix_licenses_license_date'), table_name='licenses')
    op.drop_index(op.f('ix_licenses_license_agency'), table_name='licenses')
    op.drop_index(op.f('ix_licenses_id'), table_name='licenses')
    op.drop_table('licenses')
    op.drop_index(op.f('ix_language_skills_resume_id'), table_name='language_skills')
    op.drop_index(op.f('ix_language_skills_level'), table_name='language_skills')
    op.drop_index(op.f('ix_language_skills_language_type'), table_name='language_skills')
    op.drop_index(op.f('ix_language_skills_id'), table_name='language_skills')
    op.drop_table('language_skills')
    op.drop_index(op.f('ix_introduction_title'), table_name='introduction')
    op.drop_index(op.f('ix_introduction_resume_id'), table_name='introduction')
    op.drop_index(op.f('ix_introduction_id'), table_name='introduction')
    op.drop_index(op.f('ix_introduction_content'), table_name='introduction')
    op.drop_table('introduction')
    op.drop_index(op.f('ix_career_history_start_date'), table_name='career_history')
    op.drop_index(op.f('ix_career_history_resume_id'), table_name='career_history')
    op.drop_index(op.f('ix_career_history_position_title'), table_name='career_history')
    op.drop_index(op.f('ix_career_history_main_role'), table_name='career_history')
    op.drop_index(op.f('ix_career_history_is_working'), table_name='career_history')
    op.drop_index(op.f('ix_career_history_id'), table_name='career_history')
    op.drop_index(op.f('ix_career_history_end_date'), table_name='career_history')
    op.drop_index(op.f('ix_career_history_department'), table_name='career_history')
    op.drop_index(op.f('ix_career_history_company_name'), table_name='career_history')
    op.drop_table('career_history')
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_title'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_profile_url'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_id'), table_name='resumes')
    op.drop_table('resumes')
    # ### end Alembic commands ###
