"""fix: Add url colume for company_post table and resume table

Revision ID: 5abf636e665f
Revises: 7c8da14e6ccd
Create Date: 2025-11-28 20:17:23.692754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5abf636e665f'
down_revision: Union[str, Sequence[str], None] = '7c8da14e6ccd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_posts', sa.Column('content_url', sa.String(), nullable=True))
    op.alter_column('company_posts', 'end_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.create_index(op.f('ix_company_posts_content_url'), 'company_posts', ['content_url'], unique=False)
    op.add_column('company_profile', sa.Column('company_image_url', sa.String(), nullable=True))
    op.create_index(op.f('ix_company_profile_company_image_url'), 'company_profile', ['company_image_url'], unique=False)
    op.add_column('resumes', sa.Column('resume_url', sa.String(), nullable=True))
    op.create_index(op.f('ix_resumes_resume_url'), 'resumes', ['resume_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resumes_resume_url'), table_name='resumes')
    op.drop_column('resumes', 'resume_url')
    op.drop_index(op.f('ix_company_profile_company_image_url'), table_name='company_profile')
    op.drop_column('company_profile', 'company_image_url')
    op.drop_index(op.f('ix_company_posts_content_url'), table_name='company_posts')
    op.alter_column('company_posts', 'end_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_column('company_posts', 'content_url')
    # ### end Alembic commands ###
