"""feat:App diagnosis_ansers table and update compose-posts table 

Revision ID: 7c8da14e6ccd
Revises: 4e76819351e2
Create Date: 2025-11-19 01:57:30.284647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c8da14e6ccd'
down_revision: Union[str, Sequence[str], None] = '4e76819351e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnosis_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('q1_answer', sa.String(), nullable=True),
    sa.Column('q2_answer', sa.String(), nullable=True),
    sa.Column('q3_answer', sa.String(), nullable=True),
    sa.Column('q4_answer', sa.String(), nullable=True),
    sa.Column('q5_answer', sa.String(), nullable=True),
    sa.Column('q6_answer', sa.String(), nullable=True),
    sa.Column('q7_answer', sa.String(), nullable=True),
    sa.Column('q8_answer', sa.String(), nullable=True),
    sa.Column('q9_answer', sa.String(), nullable=True),
    sa.Column('q10_answer', sa.String(), nullable=True),
    sa.Column('q11_answer', sa.String(), nullable=True),
    sa.Column('q12_answer', sa.String(), nullable=True),
    sa.Column('q13_answer', sa.String(), nullable=True),
    sa.Column('q14_answer', sa.String(), nullable=True),
    sa.Column('q15_answer', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnosis_answers_id'), 'diagnosis_answers', ['id'], unique=False)
    op.create_index(op.f('ix_diagnosis_answers_q10_answer'), 'diagnosis_answers', ['q10_answer'], unique=False)
    op.create_index(op.f('ix_diagnosis_answers_q11_answer'), 'diagnosis_answers', ['q11_answer'], unique=False)
    op.create_index(op.f('ix_diagnosis_answers_q12_answer'), 'diagnosis_answers', ['q12_answer'], unique=False)
    op.create_index(op.f('ix_diagnosis_answers_q13_answer'), 'diagnosis_answers', ['q13_answer'], unique=False)
    op.create_index(op.f('ix_diagnosis_answers_q14_answer'), 'diagnosis_answers', ['q14_answer'], unique=False)
    op.create_index(op.f('ix_diagnosis_answers_q15_answer'), 'diagnosis_answers', ['q15_answer'], unique=False)
    op.create_index(op.f('ix_diagnosis_answers_q1_answer'), 'diagnosis_answers', ['q1_answer'], unique=False)
    op.create_index(op.f('ix_diagnosis_answers_q2_answer'), 'diagnosis_answers', ['q2_answer'], unique=False)
    op.create_index(op.f('ix_diagnosis_answers_q3_answer'), 'diagnosis_answers', ['q3_answer'], unique=False)
    op.create_index(op.f('ix_diagnosis_answers_q4_answer'), 'diagnosis_answers', ['q4_answer'], unique=False)
    op.create_index(op.f('ix_diagnosis_answers_q5_answer'), 'diagnosis_answers', ['q5_answer'], unique=False)
    op.create_index(op.f('ix_diagnosis_answers_q6_answer'), 'diagnosis_answers', ['q6_answer'], unique=False)
    op.create_index(op.f('ix_diagnosis_answers_q7_answer'), 'diagnosis_answers', ['q7_answer'], unique=False)
    op.create_index(op.f('ix_diagnosis_answers_q8_answer'), 'diagnosis_answers', ['q8_answer'], unique=False)
    op.create_index(op.f('ix_diagnosis_answers_q9_answer'), 'diagnosis_answers', ['q9_answer'], unique=False)
    op.create_index(op.f('ix_diagnosis_answers_total_score'), 'diagnosis_answers', ['total_score'], unique=False)
    op.alter_column('company_posts', 'work_experience',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company_posts', 'work_experience',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_diagnosis_answers_total_score'), table_name='diagnosis_answers')
    op.drop_index(op.f('ix_diagnosis_answers_q9_answer'), table_name='diagnosis_answers')
    op.drop_index(op.f('ix_diagnosis_answers_q8_answer'), table_name='diagnosis_answers')
    op.drop_index(op.f('ix_diagnosis_answers_q7_answer'), table_name='diagnosis_answers')
    op.drop_index(op.f('ix_diagnosis_answers_q6_answer'), table_name='diagnosis_answers')
    op.drop_index(op.f('ix_diagnosis_answers_q5_answer'), table_name='diagnosis_answers')
    op.drop_index(op.f('ix_diagnosis_answers_q4_answer'), table_name='diagnosis_answers')
    op.drop_index(op.f('ix_diagnosis_answers_q3_answer'), table_name='diagnosis_answers')
    op.drop_index(op.f('ix_diagnosis_answers_q2_answer'), table_name='diagnosis_answers')
    op.drop_index(op.f('ix_diagnosis_answers_q1_answer'), table_name='diagnosis_answers')
    op.drop_index(op.f('ix_diagnosis_answers_q15_answer'), table_name='diagnosis_answers')
    op.drop_index(op.f('ix_diagnosis_answers_q14_answer'), table_name='diagnosis_answers')
    op.drop_index(op.f('ix_diagnosis_answers_q13_answer'), table_name='diagnosis_answers')
    op.drop_index(op.f('ix_diagnosis_answers_q12_answer'), table_name='diagnosis_answers')
    op.drop_index(op.f('ix_diagnosis_answers_q11_answer'), table_name='diagnosis_answers')
    op.drop_index(op.f('ix_diagnosis_answers_q10_answer'), table_name='diagnosis_answers')
    op.drop_index(op.f('ix_diagnosis_answers_id'), table_name='diagnosis_answers')
    op.drop_table('diagnosis_answers')
    # ### end Alembic commands ###
