"""Add user_gubun column to users table

Revision ID: a0ef5f301be7
Revises: 5abf636e665f
Create Date: 2025-12-03 02:30:28.759064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0ef5f301be7'
down_revision: Union[str, Sequence[str], None] = '5abf636e665f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_gubun', sa.String(), server_default='user', nullable=False))
    op.create_index(op.f('ix_users_user_gubun'), 'users', ['user_gubun'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_gubun'), table_name='users')
    op.drop_column('users', 'user_gubun')
    # ### end Alembic commands ###
