"""modified table name, table relationship

Revision ID: aa2b3d734427
Revises: a818146068be
Create Date: 2025-10-25 15:51:28.983445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa2b3d734427'
down_revision: Union[str, Sequence[str], None] = 'a818146068be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1단계: profiles 테이블 구조 변경 (user_id를 PRIMARY KEY로)
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=True)
    op.drop_constraint(op.f('profiles_user_id_fkey'), 'profiles', type_='foreignkey')
    op.create_foreign_key(None, 'profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('profiles', 'id')
    
    # 2단계: contacts 테이블 구조 변경 (user_id를 PRIMARY KEY로)
    op.drop_index(op.f('ix_contacts_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_user_id'), table_name='contacts')
    op.create_index(op.f('ix_contacts_user_id'), 'contacts', ['user_id'], unique=True)
    op.drop_constraint(op.f('contacts_user_id_fkey'), 'contacts', type_='foreignkey')
    op.create_foreign_key(None, 'contacts', 'profiles', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_column('contacts', 'id')
    
    # 3단계: 이제 account_config 테이블 생성 (profiles.user_id가 이미 PRIMARY KEY임)
    op.create_table('account_config',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sns_message_notice', sa.Boolean(), nullable=False),
    sa.Column('email_notice', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_account_config_email_notice'), 'account_config', ['email_notice'], unique=False)
    op.create_index(op.f('ix_account_config_sns_message_notice'), 'account_config', ['sns_message_notice'], unique=False)
    op.create_index(op.f('ix_account_config_user_id'), 'account_config', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.create_foreign_key(op.f('profiles_user_id_fkey'), 'profiles', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=False)
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    op.add_column('contacts', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.create_foreign_key(op.f('contacts_user_id_fkey'), 'contacts', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_contacts_user_id'), table_name='contacts')
    op.create_index(op.f('ix_contacts_user_id'), 'contacts', ['user_id'], unique=False)
    op.create_index(op.f('ix_contacts_id'), 'contacts', ['id'], unique=False)
    op.drop_index(op.f('ix_account_config_user_id'), table_name='account_config')
    op.drop_index(op.f('ix_account_config_sns_message_notice'), table_name='account_config')
    op.drop_index(op.f('ix_account_config_email_notice'), table_name='account_config')
    op.drop_table('account_config')
    # ### end Alembic commands ###
