"""modified positions nullable

Revision ID: f5095d37f0eb
Revises: 4970d924d54a
Create Date: 2025-12-16 23:09:23.427321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5095d37f0eb'
down_revision: Union[str, Sequence[str], None] = '4970d924d54a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('positions', 'code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_positions_code'), table_name='positions')
    op.create_index(op.f('ix_positions_code'), 'positions', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_positions_code'), table_name='positions')
    op.create_index(op.f('ix_positions_code'), 'positions', ['code'], unique=False)
    op.alter_column('positions', 'code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
